logger:
    version: 1
    disable_existing_loggers: true

    formatters:
        default:
            format: "[%(processName)s] %(name)s - %(levelname)s: %(message)s"
        debug:
            format: "%(asctime)s - [%(process)d] %(name)s - %(levelname)s: %(message)s"

    handlers:
        syslog:
            class: logging.handlers.SysLogHandler
            level: INFO
            formatter: default
            address: /dev/log
            facility: local0

    #   rotating_file:
    #        class: logging.handlers.RotatingFileHandler
    #        level: DEBUG
    #        formatter: debug
    #        filename: /var/log/pumpmeup.log
    #        maxBytes: 10485760 # 10MB
    #        backupCount: 20
    #        encoding: utf8

        stdout:
            class: logging.StreamHandler
            level: DEBUG
            stream: ext://sys.stdout
            formatter: debug

    root:
        level: DEBUG
        handlers: [stdout]
        propagate: no

    loggers:
        main:
            level: INFO
            handlers: [syslog]
            propagate: no

thermostat:
    pin: board.D4
    type: 'DHT22'
    interval: 60
    location:
        floor: 'basement'
        room: 'study'