mqtt:
  client_name: PMUInfluxBridge
  broker: 127.0.0.1
  topic: 
    - ['v1/+/+/+/temperature',2]
    - ['v1/+/+/+/humidity',2]
  regex: '^v1/(?P<place>[^/]+)/(?P<floor>[^/]+)/(?P<room>[^/]+)/(?P<measurement>[^/]+)$'
influxdb:
  address: 127.0.0.1
  user: mqttuser
  password: super_secret_password
  database: database

